let menuObj=[
    {
        index:'1',
        title:"处理中心",
        url:"",
        disabled:false
    },{
        index:'2',
        title:"我的工作台",
        url:"",
        disabled:false,
        children:[
            {
                index:"2-1",
                title:"首页",
                url:"/home/index",
                disabled:false
            },
            {
                index:"2-2",
                title:"视频",
                url:"/home/video",
                disabled:false
            },
            {
                index:"2-3",
                title:"选项1",
                url:"/home/video",
                disabled:true
            }
        ]
    },{
        index:'3',
        title:"消息中心",
        url:"",
        disabled:false
    }
]
export default menuObj;